### DISCUSSION TITLE
AP2 on Windows WSL2

### DISCUSSION THREAD

**Discussion by noelhibbard** [mikebrady/shairport-sync#1242] [Show and tell]
Insider builds of Windows 10 have functioning audio out of the box. No trickery is needed. I haven't tried but you may be able to get SPS working on non-insider builds too by installing pulseaudio server in windows and then configuring WSL2 to point to it. But if you are on the insider dev build, these steps worked for me on Umbuntu in WSL2. Haven't looked into a way to keep it alive though.

# Build/Install
```bash
sudo apt update
sudo apt-get install -y build-essential sudo git xmltoman autoconf automake libtool \
    libpopt-dev libconfig-dev libasound2-dev avahi-daemon libavahi-client-dev libssl-dev libsoxr-dev libglib2.0-dev \
    libplist-dev libsodium-dev libavutil-dev libavcodec-dev libavformat-dev uuid-dev libgcrypt-dev libpulse-dev \
    libmosquitto-dev pulseaudio pulseaudio-utils libsndfile1-dev

git clone https://github.com/mikebrady/nqptp.git ~/nqptp
cd ~/nqptp
autoreconf -fi
./configure
make
sudo make install

git clone https://github.com/mikebrady/alac.git ~/alac
cd ~/alac
autoreconf -fi
./configure
make
sudo make install

git clone https://github.com/mikebrady/shairport-sync.git -b development ~/shairport-sync
cd ~/shairport-sync
autoreconf -fi
./configure --sysconfdir=/etc --with-soxr --with-ssl=openssl --with-avahi --with-airplay-2 --with-mqtt-client --with-pa --with-convolution
make -j
sudo make install
```

# Run
```bash
sudo service dbus start
sudo service avahi-daemon start
sudo nqptp &
shairport-sync
```

**Comment by noelhibbard** [comment]
I forgot to add, you need to have WSL set to run on your host network. To do this:
- Run Hyper-V Manager
- Click "Virtual Switch Manager" on the right
- Click on the WSL switch
- Select "External Network" and then select the NIC you want it to bind to (you will need to stop all WSL instances first or else it will fail)

Now in the WSL instance run these commands so it will pick up an IP from DHCP on the host network:
```bash
sudo ip addr flush dev eth0
sudo dhclient eth0
```

**Comment by noelhibbard** [comment]
This utility will get systemd working in WSL so then you can run nqptp and shairport-sync as services in WSL just as you would a normal Linux distro.

https://github.com/arkane-systems/genie

**Reply by hyunjongL** [reply]
Are you still using this setup? How's the overhead of running this 24/7 on a workstation?

**Reply by noelhibbard** [reply]
I do not. I am back to the old Cygwin build of the AP1 version of shairport-sync.

**Reply by hyunjongL** [reply]
Thanks, I guess I might also stick to the Cygwin airplay1

**Comment by noelhibbard** [comment]
I just took a stab at this on Windows 11 23H2 (and still works in Win11 25H2) and the process is easier now. Microsoft made it really easy to put WSL directly on your real network. You just need to make a VM switch that is a bridged to one of your network adapters. You can do this in powershell like this:
```powershell
New-VMSwitch -Name "Bridge" -NetAdapterName (Get-NetAdapter|Sort ifIndex)[0].Name -AllowManagementOs $true
```

Then tell wsl to use bridge mode and bind it to the VM switch you just created like this.

%USERPROFILE%\\.wslconfig:
```
[wsl2]
networkingMode=bridged
vmSwitch=Bridge # This is the name of the adapter you created with the powershell command above
```

Then restart wsl:
```powershell
wsl --shutdown
```

docker-compose.yaml:
```yaml
# Example docker compose config.

services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    # environment:
    #  S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file
    #  PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
    #  PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    #  XDG_RUNTIME_DIR: /tmp # Path for pipewire
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
      - /mnt/wslg/PulseServer:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
    #   - /run/user/1000/pipewire-0:/tmp/pipewire-0 # Pipewire socket when using pipewire
    # command: -o pw # You can specify the desired output with command:
    logging:
      options:
        max-size: "200k"
        max-file: "10"
```

shairport-sync.conf:
```
general =
{
	name: "Noel's Desk";
	output_backend = "pa";
	resync_threshold_in_seconds = 0; // Without this, playback never starts.
}
```
