### DISCUSSION TITLE
Run multiple SPS-AP2 instances in Docker

### DISCUSSION THREAD

**Discussion by noelhibbard** [mikebrady/shairport-sync#1374] [Show and tell]
So I just discovered a way to run multiple instances of SPS-AP2 in Docker containers that each have their own IP on the host network.

First you need to create a new Docker network like this:
```bash
docker network create -d macvlan \
   --subnet=192.168.18.0/24 \
   --gateway=192.168.18.254 \
   -o parent=eno1 spsnet
```

In the above command, you eno1 is the physical network interface on your host machine. The subnet and gateway need to match your host networks subnet and gateway. I am naming this network spsnet.

Now when you run the first instance of shairport-sync, do it like this:
```bash
docker run -d --name FirstInstance --restart unless-stopped --net spsnet \
    --ip 192.168.18.81 \
    -v /opt/shairport-sync/FirstInstance.conf:/etc/shairport-sync.conf \
    -v /etc/asound.conf:/etc/asound.conf
    --device /dev/snd mikebrady/shairport-sync:unstable-development
```

And the second instance like this:
```bash
docker run -d --name SecondInstance --restart unless-stopped --net spsnet \
    --ip 192.168.18.82 \
    -v /opt/shairport-sync/SecondInstance.conf:/etc/shairport-sync.conf \
    -v /etc/asound.conf:/etc/asound.conf
    --device /dev/snd mikebrady/shairport-sync:unstable-development
```

You can see I am also mapping in a custom shairport-sync.conf into each container. I have also specified a static IP for each container. You would need to make sure these statics aren't already in use on your network.

The only hang up I am having is with my elaborate alsa config. My asound.conf busts a single 7.1 card into multiple cards. It works fine on the host but for some reason the containers complain that the card is in use. I can connect and play to the FirstInstance and sound comes out of the correct output. I can then disconnect from the FirstInstance and then connect and play to the SeccondInstance and the audio comes out of the other output. I just can't play to both instances at the same time because SPS complained that the output is busy. ALSA dmix just doesn't seem to work correctly in Docker containers.

It looks like the only way for this to really work would be having fully discrete sound cards for each instance and let each instance have exclusive access to each card. I'm amazed there isn't more talk about ALSA and dmix in Docker. Seems the whole world uses Pulse for everything these days.

mikebrady/shairport-sync:unstable-development doesn't have Pulse support so I'll have to make my own image but I suspect I can get it to work with Pulse. I feel like I am close to having a super easy to deploy way of running multiple SPS-AP2 instances without a stack of Raspberry Pi's.

**Comment by noelhibbard** [comment]
I got pulseaudio working on my host as a system wide systemd service and the docker containers are configured to reach the host via unix:/var/run/pulse/native. I managed to spin up two instances, both pointed at the same PA sink. I have fairly good sync when testing with a set of headphones. Now I have to remember how to add sinks to PA. I will write this whole process up and share my docker-compose.yaml once I have it all nailed down.

**Comment by noelhibbard** [comment]
So I have this working with two cards in a test server that is freshly loaded with Debian Bullseye. I have PulseAudio running as a system wide systemd service and for whatever reason on a reboot it doesn't properly add all my ALSA sinks. All I have to do is restart the pulseaudio service and they all show up. My work around is to create a bash script that checks to see if all the sinks are there and if not it restarts the service. I then have a docker compose for each shairport-sync instance. It's working really well, sync is perfect. I tested with the left headphone of one instance and the right headphone from the other instance.

So the basic steps are:
- Bare minimum Debian install.
- Install PulseAudio.
- Add root to the audio and pulse-access groups.
- Add pulse to the audio group.
- Disable the usermode PA service.
- Create a system wide PA service and start it.
- Edit /etc/pulse/system.pa to add sinks for any ALSA outputs you plan to use.
- Clone the shairport-sync dev branch and then make a few changes to the Dockerfile to add --with-pa and then build the image.

And here is a sample docker-compose.yaml that will automatically create the macvlan network (I named it spsnet):
```yaml
services:
  shairport-sync:
    container_name: SPS-Livingroom
    image: shairport-sync:unstable-development
    restart: unless-stopped
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf
      - /var/run/pulse:/var/run/pulse
    environment:
      - PULSE_SERVER=unix:/var/run/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    networks:
      spsnet:
        ipv4_address: 192.168.1.100 # Static IP assign to the container. Make sure it's not already in use on the host network
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: eno1 # Physical network interface on host that we want to bind to
    ipam:
      config:
        - subnet: 192.168.1.0/24 # This needs to match the subnet of your host network
          gateway: 192.168.1.254
```

I will write up something more formal and create a GitHub repo with the README.md and the pulseaudio.service I am using.

I really wish I could figure out why PulseAudio fails to pickup my ALSA sinks on a reboot without restarting the service. That is the one thing that convoluts the whole thing. It would also be nice if the container could pull an IP from DHCP but I was unable to find a way to do that,

**Reply by charlesomer** [reply]
Hmm this looks interesting, I think I tried this before but couldn't get it working but I'm glad you were able to! Unfortunately I've still not been able to get this working though, it might be because I'm using `wlan0` on my Pi instead? Have you had any luck doing it wirelessly? I'm not sure why this would make a difference though :/

**Reply by noelhibbard** [reply]
Did you use the macvlan driver? I haven't tried wireless but don't see why it would make a difference. I'm running on a full sized Intel machine over ethernet. I have a spare RPi3B that I will reload and then see if I can get multiple docker instances to work on the wireless adapter.

It's working really well for me. The only network related issue I've run into is the containers can not access the host. They can access anything on the host network, just not the host itself. It turns out this is normal for a macvlan network. One of my SPS instances is setup to call a script that does some CURL requests on setvol, start and stop but it was failing to reach the host IP. The workaround was to bind the containers to two networks. Most people don't need to access the host from the containers so it's not a big deal.

Here is my current docker-compose.yaml. You will also notice I'm adding a host record for server1 so that it overrides the DNS lookup.
```yaml
services:
  SPS-Bathroom:
    container_name: SPS-Bathroom
    image: shairport-sync:unstable-development
    restart: unless-stopped
    extra_hosts:
      - "server1:172.18.0.1"
    volumes:
      - ./shairport-sync-bathroom.conf:/etc/shairport-sync.conf
      - /var/run/pulse:/var/run/pulse
      - ./scripts:/opt/shairport-sync
    environment:
      - PULSE_SERVER=unix:/var/run/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    networks:
      spsnet_bridge:
      spsnet:
        ipv4_address: 10.18.11.1
  SPS-Livingroom:
    container_name: SPS-Livingroom
    image: shairport-sync:unstable-development
    restart: unless-stopped
    extra_hosts:
      - "server1:172.18.0.1"
    volumes:
      - ./shairport-sync-livingroom.conf:/etc/shairport-sync.conf
      - /var/run/pulse:/var/run/pulse
      - ./scripts:/opt/shairport-sync
    environment:
      - PULSE_SERVER=unix:/var/run/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    networks:
      spsnet_bridge:
      spsnet:
        ipv4_address: 10.18.11.2
  SPS-Porch:
    container_name: SPS-Porch
    image: shairport-sync:unstable-development
    restart: unless-stopped
    extra_hosts:
      - "server1:172.18.0.1"
    volumes:
      - ./shairport-sync-porch.conf:/etc/shairport-sync.conf
      - /var/run/pulse:/var/run/pulse
      - ./scripts:/opt/shairport-sync
    environment:
      - PULSE_SERVER=unix:/var/run/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    networks:
      spsnet_bridge:
      spsnet:
        ipv4_address: 10.18.11.3
  SPS-Garage:
    container_name: SPS-Garage
    image: shairport-sync:unstable-development
    restart: unless-stopped
    extra_hosts:
      - "server1:172.18.0.1"
    volumes:
      - ./shairport-sync-garage.conf:/etc/shairport-sync.conf
      - /var/run/pulse:/var/run/pulse
      - ./scripts:/opt/shairport-sync
    environment:
      - PULSE_SERVER=unix:/var/run/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    networks:
      spsnet_bridge:
      spsnet:
        ipv4_address: 10.18.11.4
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - subnet: 10.18.0.0/16
          gateway: 10.18.3.1
  spsnet_bridge:
    name: spsnet_bridge
    driver: bridge
```
