### DISCUSSION TITLE
Docker and Pulse audio

### DISCUSSION THREAD

**Discussion by spiro-c** [mikebrady/shairport-sync#1620] [Show and tell]
I notice there is some talks about docker image and pulseaudio I have look how is this implemented in balena-sound [script](https://github.com/balena-labs-projects/balena-sound/blob/f2d18081def8d7d5ef5cd9adb28c07bab5048df2/plugins/airplay/Dockerfile.template#L12) they install just `alsa-plugin-pulse`  and whit small changes to the S6-overlay scripts I was able to use the docker image and pulseaudio here is my working [docker-compose example](https://github.com/spiro-c/shairport-sync-docker-pulse) 

I make `pulseaudio` and `shairport-sync` service files where the `pulseaudio` service is checking if `PULSE_SERVER` env variable is passed and install the `alsa-plugin-pulse`  if not it will continue and start like normal and other services dependent on pulse shairport-sync dependent on all other service so it start last
From the host server the pulseaudio socket and pulseaudio cookie need to be mount inside the container cookie is needed for root user from inside container to login to the pulseaudio server

there is also `EXTRA_ARGS` env variable that is pass to the `shairport-sync ` for extra option if need to be used  for setting the NAME config file... 
If there is interest in this i can make PR for changes in the `s6-overley` scripts

**Comment by mikebrady** [comment]
Thanks for the information. TBH, I'd prefer to keep PulseAudio out of the Docker image, but the modified Docker compose script would certainly be interesting. A quick guide to that would be useful!

**Comment by lyuzashi** [comment]
Not sure if this would interest anyone but I've created a Docker image which uses `mikebrady/shairport-sync` as a base and adds Alsa config to use the Pulse plugin to enable sending audio through the host's Pulse Audio socket.

Seems to be working on desktop Ubuntu.

I haven't extensively tested the sync impacts.

![Screen Shot 2023-03-28 at 12 55 50 pm](https://user-images.githubusercontent.com/802833/228106807-22a3ec36-ae00-448e-bf59-6331161532dd.png)


https://hub.docker.com/r/lyuzashi/shairport-sync-pulse

**Comment by almereyda** [comment]
I'm documenting another setup that uses the latest `mikebrady/shairport-sync` image, but with anonymous authentication, since the cookie wouldn't be picked up anymore (PulseAudio logs `Denied access to client with invalid authentication data.`). This is running unprivileged and headless on an Ubuntu 22.04 server installation on a Raspberry Pi 4 using the HifiBerry DAC+ shield.

```sh
$ diff /etc/pulse/default.pa ~/.config/pulse/default.pa
```

```diff
78c78
< load-module module-native-protocol-unix
---
> load-module module-native-protocol-unix auth-anonymous=1
```

`compose.yml`:

```yaml
services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
# For debugging, enter a shell with docker compose run --rm --entrypoint /bin/ash shairport-sync
#    restart: "no"
#    user: shairport-sync
    environment:
      PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
      PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    #devices:
    #  - "/dev/snd" # ALSA device
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
      - ./.state/coverart:/tmp/shairport-sync/.cache/coverart
      - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
      - /home/ubuntu/.config/pulse/cookie:/tmp/pulseaudio.cookie
```

And with the following custom configuration:

```sh
# diff <(curl -sSL https://github.com/mikebrady/shairport-sync/raw/master/scripts/shairport-sync.conf) shairport-sync.conf
```

```diff
9c9
< //    name = "%H"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
---
>       name = "soundsystem"; // The container receives an auto-generated hostname. We choose to set our instance configuration here instead.
19c19
< //    output_backend = "alsa"; // Run "shairport-sync -h" to get a list of all output_backends, e.g. "alsa", "pipe", "stdout". The default is the first one.
---
>       output_backend = "pa";
21c21
< //    interface = "name"; // Use this advanced setting to specify the interface on which Shairport Sync should provide its service. Leave it commented out to get the default, which is to select the interface(s) automatically.
---
>       interface = "eth0:0";
174c174
< //    application_name = "Shairport Sync"; //Set this to the name that should appear in the Sounds "Applications" tab when Shairport Sync is active.
---
>       application_name = "soundsystem";
```

References:

- [pulseaudio - System-wide audio (including bluetooth device) support on 24.04 - Ask Ubuntu](https://askubuntu.com/questions/1512015/system-wide-audio-including-bluetooth-device-support-on-24-04)
- [[Problem]: Sound only works from one docker instance at a time · Issue #1694 · mikebrady/shairport-sync](https://github.com/mikebrady/shairport-sync/issues/1694#issuecomment-1604320339)
