### DISCUSSION TITLE
Multiple instances (docker) ALSA and Pulse Audio Configuration

### DISCUSSION THREAD

**Discussion by glasscake** [mikebrady/shairport-sync#1883] [Q&A]
Running on Debian 12. 1 usb DAC, trying to have the audio from two instances split into the left and right channel of the usb dac.

I started with just ALSA and made two plugs with just the left / right channel in the asound.conf file. from this guide :
https://bootlin.com/blog/audio-multi-channel-routing-and-mixing-using-alsalib/
I got that working but ran into the device being locked when trying to play simultaneously. IPC=Host on the containers did not fix this issue either.

So now ive moved to pulse and with a pulse sink to the ALSA hardware directly I get output again. I can not get it to give me output on my plugs configured in asound.conf. so the following gives me output on both channels:
load-module module-alsa-sink device=hw:0 sink_name=pamaster

But now I cant get it to output to one of my asound.conf plugs, dmix, dshare. anything. 
load-module module-alsa-sink device=out0 sink_name=paout0
gives me no output.

I tried to pivot and use just pulse audio to do the splitting but I get errors. (not at my computer right now so i cant specify what errors)
load-module module-alsa-sink device=hw:0 sink_name=pamaster
load-module module-remap-sink sink_name=paleftonly master=pamaster channels=1 master_channel_map=front-left channel_map=front-left remix=no

I think im close here, but there must be something slightly wrong in my context. 

Super awesome project btw, I know the multiple instances is defiantly niche and difficult to setup. If anyone could help me out that would be much appreciated ive given this a good 8-10 hours of troubleshooting. and to be honest its probably easier to just buy multiple usb dacs, ignore the second channel, and give each instance its own dac lol.

Thanks in advance.

**Comment by noelhibbard** [comment]
So I went the PipeWire route for a while with high hopes seeing how it seems to be the latest and greatest but I've decided it's a pile of dog shiiit and decided to giving pure ALSA a shot again. In the past I had issues with the container complaining about the device being busy eveh though I could play to both at the same time on the host at the same time. I remembered reading somewhere around here that it was an IPC related issue that was solved with a docker config change. So searching around I found your post here and ```ipc: host``` in my docker compose did the trick for me. So I wanted to post saying thanks, but also wanted to share some details on how I accomplished what you are trying to do in PA.

In my alsa config I have this to make a dmix for one of my 5.1ch cards:
```
pcm.card1_dmix {
    type dmix
    ipc_key 2048
    slave {
        pcm "hw:CARD=card1,DEV=1"
        period_time 0
        period_size 1024
        buffer_size 4096
        channels 6
    }
    bindings {
        0 0
        1 1
        2 2
        3 3
        4 4
        5 5
    }
}
```

Then in my PA config I have these entries to take two channels from my 5.1ch card and make them look like two stereo outputs for use in shairport-sync:
```
load-module module-alsa-sink device=card1_dmix sink_name=card1

# Kitchen
load-module module-remap-sink sink_name=Kitchen master=card1 channels=2 master_channel_map=front-right,front-right channel_map=front-left,front-right remix=no

# Guest Bathroom
load-module module-remap-sink sink_name=GuestBath master=card1 channels=2 master_channel_map=front-left,front-left channel_map=front-left,front-right remix=no
```

My docker compose looks something like this:
```yaml
services:
  Kitchen:
    container_name: Kitchen
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    volumes:
      - /var/run/pulse:/var/run/pulse # <- this may need adjusting to match the environment on your host. Your host OS my put the pulse socket/cookie somewhere else.
      - ./shairport-sync-Kitchen.conf:/etc/shairport-sync.conf
    networks:
      - spsnet_shared
      - spsnet
  Guest_Bathroom:
    container_name: Guest_Bathroom
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    volumes:
      - /var/run/pulse:/var/run/pulse
      - ./shairport-sync-Guest_Bathroom.conf:/etc/shairport-sync.conf
    networks:
      - spsnet_shared
      - spsnet
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: enp6s0 # <- this should match the NIC on your host which you want sps to run on
    ipam:
      config:
        - subnet: 10.18.0.0/16 # <- this should be the subnet on your host which you want sps to run on
          ip_range: 10.18.15.0/29 # <- this should point to an unused block of IPs within your main subnet. For example, outside your DHCP range.
          gateway: 10.18.3.1
  spsnet_shared:
    name: spsnet_shared
    driver: bridge

```

And the relevant parts of the shairport-sync.conf:
```
general =
{
	name = "Kitchen";
	output_backend = "pa";
}
pa =
{
	server = "unix:/var/run/pulse/native"; // <- this needs match the container side of the volume map in your docker compose
	sink = "Kitchen";
};
```

Hope this helps and thanks for the ```ipc: host``` tip! I'm always learning something new in docker.

**Reply by glasscake** [reply]
Where did you end up putting the ipc: host in your compose file I don't see it in your example code.
and I am glad to hear it worked for you; I ended up going with 7 DACs using only 1 channel, I may try to redo this setup with a raspberry pi & its HDMI port to an amp.

**Reply by noelhibbard** [reply]
I only need that setting in my new setup which is pure ALSA. When using PA it's not needed. I was just supplying some details from my old PA setup since that is what you were attempting in your original post.

**Reply by glasscake** [reply]
If possible it would be very appreciated if you shared your full stack for splitting up a DAC using pure ALSA. That was the original route I tried taking and never found success without using multiple DACs.

alsaconfig, docker compose, shairport-sync.conf and any other files applicable would be awesome!

Thanks!

**Reply by noelhibbard** [reply]
Sure, no problem.

### /etc/asound.conf
```
# USBAudio1
pcm.usb_audio_1 {
    type plug
    slave.pcm "dmix:USBAudio1"
    slave.rate 48000
    slave.channels 2
    ttable.0.0 1
    ttable.1.1 1
}
pcm.usb_audio_1_1 {
    type plug
    slave.pcm "dmix:USBAudio1"
    slave.rate 48000
    slave.channels 2
    ttable.0.1 1
    ttable.1.1 1
}
pcm.usb_audio_1_2 {
    type plug
    slave.pcm "dmix:USBAudio2"
    slave.rate 48000
    slave.channels 2
    ttable.0.0 1
    ttable.1.0 1
}
```

### docker-compose.yaml
```yaml
services:
  Kitchen:
    container_name: Kitchen
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    ipc: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /etc/asound.conf:/etc/asound.conf
      - ./shairport-sync-Kitchen.conf:/etc/shairport-sync.conf
    networks:
      - spsnet_shared
      - spsnet
  Guest_Bathroom:
    container_name: Guest_Bathroom
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    ipc: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /etc/asound.conf:/etc/asound.conf
      - ./shairport-sync-Guest_Bathroom.conf:/etc/shairport-sync.conf
    networks:
      - spsnet_shared
      - spsnet
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: enp6s0
    ipam:
      config:
        - subnet: 10.18.0.0/16
          ip_range: 10.18.15.0/29
          gateway: 10.18.3.1
  spsnet_shared:
    name: spsnet_shared
    driver: bridge
```

### ./shairport-sync-Kitchen.conf
```
general =
{
	name = "Kitchen"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
	output_backend = "alsa"; // Run "shairport-sync -h" to get a list of all output_backends, e.g. "alsa", "pipe", "stdout". The default is the first one.
};

alsa =
{
	output_device = "usb_audio_2_1"; // the name of the alsa output device. Use "shairport-sync -h" to discover the names of ALSA hardware devices. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
};
```

### ./shairport-sync-Guest_Bathroom.conf
```
general =
{
	name = "Guest Bathroom"; // This means "Hostname" -- see below. This is the name the service will advertise to iTunes.
	output_backend = "alsa"; // Run "shairport-sync -h" to get a list of all output_backends, e.g. "alsa", "pipe", "stdout". The default is the first one.
};

alsa =
{
	output_device = "usb_audio_2_2"; // the name of the alsa output device. Use "shairport-sync -h" to discover the names of ALSA hardware devices. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
};
```

Take note that the spsnet_shared network isn't mandatory. It's there to give the container access to the host network for things like MQTT or for example a session control script that uses curl to control an AVR.

Also note that pcm.usb_audio_1 isn't really needed for this spesific config. I have a bunch of USB cards all mounted inside a box with a USB hub, a handful of small 40/40 watt amps powered by an ATX power supply with a bunch of banana plugs on the outside that are labeled something like this:
```
    1.1
1 -
    1.2

    2.1
2 -
    2.2
```

So if I plug the kitchen into the port labeled 2.2, I know to address it in the config as usb_audio_2_2. If I plug the Livingroom AVR into both 1.1 and 1.2, I would address it in the config as usb_audio_1.
