### DISCUSSION TITLE
PipeWire in the official Docker image

### DISCUSSION THREAD

**Discussion by noelhibbard** [mikebrady/shairport-sync#1940] [Q&A]
So I am trying to make the switch to PipeWire but I'm having issues. I have pipewire working on the host with no issue. When I try to get it up in the container I am getting this in the sps logs:
```Shairport Sync's PipeWire backend can not get timing information from the PipeWire system. Is PipeWire running?```

I shelled into the container and then installed the ```pipewire-tools``` and ```sox``` packages and then I am able to play /dev/random to pipewire and I'm hearing static. So pw does seem to be working in the container.

Today is my first attempt at using pipewire on any system at all. Any ideas?

More info on my setup. I'm on a fresh install of Debian Bookworm. I edited the systemd service so that it will run as root. Here is my docker compose:
```yml
services:
  Instance1:
    container_name: Instance1
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    environment:
    #  S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file
      XDG_RUNTIME_DIR: /tmp # Path for pipewire
    volumes:
      - ./shairport-sync-instance1.conf:/etc/shairport-sync.conf
      - /run/user/0/pipewire-0:/tmp/pipewire-0
    networks:
      - spsnet_shared
      - spsnet

networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 10.1.0.0/22
          ip_range: 10.1.3.88/29
          gateway: 10.1.3.1
  spsnet_shared:
    name: spsnet_shared
    driver: bridge
```

**Comment by mikebrady** [comment]
I must confess that I haven't used PipeWire insider Docker -- it was added in response to a request. Looking on the web, there seems to be some guidance, e.g. [here](https://stackoverflow.com/questions/68973199/pipewire-audio-in-fedora-container), but I guess you've tried all that?

**Reply by noelhibbard** [reply]
Actually, I hadn't seen that one. I'll take a look. I mostly looked around here because I have PW working fine in the container, just not in sps. Everything I read in this repo about PW in docker seems to be people using the PA backend to go through PW.

**Reply by mikebrady** [reply]
Fair enough. Slightly separately, my experience with PipeWire is that its latencies seem considerably more stable than PulseAudio's.

**Reply by noelhibbard** [reply]
That is exactly why I wanted to make the switch. Still not having any luck in the container but at least I'm getting the hang of how to configure pipewire/wireplumber. I have it how I want it now, so I'm going back to getting it working in sps and still getting the same error, despite being able to test via pw-play from within the container.

**Reply by noelhibbard** [reply]
> Slightly separately, my experience with PipeWire is that its latencies seem considerably more stable than PulseAudio's.

After a month or so with PW in the official Docker image I can confidently say it has the most stable sync of any setup I've had to date. The sync is perfect, even after hours of use, and after adding, removing, re-adding targets, it never drifts. I can finally have music in every room and be able to walk from room to room without it sounding strange.

**Comment by noelhibbard** [comment]
Solved. I needed the to use ```S6_KEEP_ENV: 1``` because otherwise ```XDG_RUNTIME_DIR: /tmp``` was getting wiped out. Not sure how pw-play was working within the container if that env var was missing.

**Reply by mikebrady** [reply]
Cool! So does that mean it’s working properly?

**Reply by noelhibbard** [reply]
> Cool! So does that mean it’s working properly?

Yep, working perfect. I have 5 identical USB sound cards which I have several instances of sps pointed to., I am testing with wired earbuds and I can put the left earbud fomr one sps instand in my left ear and the right ear bud from another instance and then stream to but with my iPhone and it's in perfect sync. I can pause/unpauce, change tracks, remove/add instances and it is always in sync.

It's cool how you can link things together dynamically with pw-link. PipeWire has abig learning curve and a lot of the apps don't work as documented, for example ```pw-ctl create-link``` does not seem to work. At least not on the arch package.

Still a lot to learn.

**Comment by zoltak** [comment]
Hi, I'm also trying to get PW working in Docker and followed the steps below. The host OS is Fedora 41

This is my docker compose file:
```
services:
  Instance1:
    container_name: Instance1
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    volumes:
      - ./shairport-sync-instance1.conf:/etc/shairport-sync.conf
      - type: bind
        source: /run/user/1000/pipewire-0
        target: /tmp/pipewire-0
      - type: bind
        source: /run/user/1000/pulse/native
        target: /tmp/pulseaudio.socket
#    devices:
#      - /dev/snd:/dev/snd
#    user: 1000:1000
    environment:
      PULSE_SERVER: unix:/tmp/pulseaudio.socket
      XDG_RUNTIME_DIR: /tmp
      PIPEWIRE_RUNTIME_DIR: /tmp
      S6_KEEP_ENV: 1
      PULSE_COOKIE: /tmp/pulseaudio.cookie
```


When I do an strace in the container running `pactl list` I get this error:
`connect(7, {sa_family=AF_UNIX, sun_path="/tmp/pulseaudio.socket"}, 110) = -1 EACCES (Permission denied)`

Within the container:
```
/ # ls -l /tmp/
total 0
srw-rw-rw-    1 shairpor shairpor         0 Jan 12 21:55 pipewire-0
srw-rw-rw-    1 shairpor shairpor         0 Jan 13  2025 pulseaudio.socket
```

Even when running under user 1000 in the container it makes no difference.

Do I need to do anything else to the config in Fedora 41 or is something wrong with the docker config? Any suggestions?

**Reply by noelhibbard** [reply]
I've stripped everything related to PA from my containers and run pure PW now. I run the container as root and everything is working perfect. It's by far the best setup I've had to date. I have 5 identical USB sound cards connected to a USB3 hub and the sync is absolutely perfect. Based on your error, I'd say you have you still have your backend set to PA rather than PW.

Edit: Never mind, the pulseaudio error you pointed out isn't coming from sps, it's coming from pactl. Something I notice a lot is people want to use PW but in the end use PA on top of PW. SPS natively supports PW, so why even bother with PA? Seems like a extra layer for no reason.

My compose.yaml looks like:
```yaml
services:
  Livingroom:
    container_name: Livingroom
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    environment:
      S6_KEEP_ENV: 1
      XDG_RUNTIME_DIR: /tmp
    volumes:
      - ./shairport-sync-Livingroom.conf:/etc/shairport-sync.conf
      - /run/user/0/pipewire-0:/tmp/pipewire-0
    networks:
      - spsnet_shared
      - spsnet
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 10.18.0.0/16
          ip_range: 10.18.15.0/29
          gateway: 10.18.3.1
  spsnet_shared:
    name: spsnet_shared
    driver: bridge
```

My shairport-sync.conf looks like:
```
general =
{
	name = "Livingroom";
	output_backend = "pw";
};

pw =
{
	application_name = "sps-Livingroom";
	node_name = "sps-Livingroom";
	sink_target = "usb-card-1-playback";
};
```

One other tidbit is my server is headless so I had to enable linger so that the pipewire service continues to run even if I close all my ssh sessions.

```bash
loginctl enable-linger root
```
