### DISCUSSION TITLE
Docker Config File

### DISCUSSION THREAD

**Discussion by PablaV** [mikebrady/shairport-sync#1984] [Q&A]
New to docker, trying to migrate over from a bare metal setup but running into the issue with finding the config file. On the bare metal install the config file was in the `/etc` directory, and when I build the container using the `-v` option I still can't seem to find where the config file is stored. Shairport does indeed show up and functions but since I cannot find the config file I am not able to set up the pipe to Owntone. 

```
docker run -d --restart unless-stopped --net host --device /dev/snd \
    mikebrady/shairport-sync:latest \
    -v --statistics
```

**Comment by PablaV** [comment]
Adding to this as my Docker expertise grow.. I set up a dock-compose file as below and get this error: 
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/arman/docker-compose/volumes/shairport-sync/shairport-sync.conf" to rootfs at "/etc/shairport-sync.conf": create mountpoint for /etc/shairport-sync.conf mount: cannot create subdirectories in "/var/lib/docker/overlay2/b5102814a1314d8bc403ab941774bab0842aaea4f4b893ae1361d04ca2ec7e36/merged/etc/shairport-sync.conf": not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
exit status 1
```
So then I went in the `/home/usr/docker-compose/volumes/shairport-sync` directory and deleted the **folder** named `Shairport-sync.conf` and replaced it with the `shairport-sync.conf` **file** I was able to get Shairport container up and running. However I made one small tweak to that config file to see if Shairport was reading it and renamed the name of the Airplay input, but Shairport is displaying the Airplay input as it would regularly, which is the device name. So it's not reading the config file. 
```
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/snd"
    volumes:
      - ./volumes/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf
    logging:
      options:
        max-size: "200k"
        max-file: "10"
```
