### ISSUE TITLE
Configuration tip: run Docker container on Linux using host dbus and avahi-daemon

### ISSUE THREAD

**Issue by robcast** [mikebrady/shairport-sync#1387]
Not a bug report but a suggestion for an optional configuration for the current s6-based unstable-development Docker container to avoid starting additional instances of dbus and avahi-daemon in the container and use the host's dbus connection instead.

1. create an empty file `down`

2. create a `docker-compose.override.yml`:
```
version: "2.1"

services:
  shairport-sync:
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
    volumes:
      - /run/dbus:/run/dbus
      - ./down:/etc/services.d/01-dbus-daemon/down:ro
      - ./down:/etc/services.d/02-avahi/down:ro
```

This configuration inhibits the dbus and avahi daemons from starting and uses the hosts system dbus instead.

I don't know if this is useful for many people and if it should be added to the documentation somewhere. Maybe an advanced configuration tips section? I created this config to control the avahi-daemon on the host to suppress network-wide announcements for shairplay-sync on the internal Docker network interface ;-)
