### ISSUE TITLE
[Problem]: Sound only works from one docker instance at a time

### ISSUE THREAD

**Issue by nhangeland** [mikebrady/shairport-sync#1694]
### What happened?

Trying to run SPS with AP2 in docker using the same sound card with multiple outputs (Scarlett 18i20).
Audio works fine for the first instance of SPS I play to, but the subsequent instances I get no audio. They work just fine individually.

### Configuration Information.

asound.conf:
```
pcm_slave.outs {
        pcm "hw:USB"
        rate 44100
        channels 10
}

pcm.livingroom {
        type plug
        slave.pcm {
                type dshare
                ipc_key 4242
                slave outs
                bindings.0 0
                bindings.1 1
        }
}

pcm.office {
        type plug
        slave.pcm {
                type dshare
                ipc_key 4242
                slave outs
                bindings.0 2
                bindings.1 3
        }
}

pcm.kitchen {
        type plug
        slave.pcm {
                type dshare
                ipc_key 4242
                slave outs
                bindings.0 4
        }
}
.....
```
docker-compose:
```
services:
  office:
    image: mikebrady/shairport-sync:development
    restart: always
    devices:
      - "/dev/snd"
    volumes:
      - ./config/office.conf:/etc/shairport-sync.conf
      - ./config/asound.conf:/etc/asound.conf
    networks:
      spsnet:
        ipv4_address: 10.0.0.202
  
  kitchen:
    image: mikebrady/shairport-sync:development
    restart: always
    devices:
      - "/dev/snd"
    volumes:
      - ./config/kitchen.conf:/etc/shairport-sync.conf
      - ./config/asound.conf:/etc/asound.conf
    networks:
      spsnet:
        ipv4_address: 10.0.0.203
  living_room:
    image: mikebrady/shairport-sync:development
    restart: always
    devices:
      - "/dev/snd"
    volumes:
      - ./config/living-room.conf:/etc/shairport-sync.conf
      - ./config/asound.conf:/etc/asound.conf
    networks:
      spsnet:
        ipv4_address: 10.0.0.206
     
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 10.0.0.0/24+
          gateway: 10.0.0.133
```
sps config:
```
general =
{
	name = "Kitchen";
	// Im using a 10 port offest for each instance and the same for the id offset
	port = 7040;
	airplay_device_id_offset = 40;
};

alsa =
{
	output_device = "kitchen";
};
```

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm
