### ISSUE TITLE
[Problem]: shairport-sync docker neither Pipewire or PulseAudio working

### ISSUE THREAD

**Issue by spmp** [mikebrady/shairport-sync#1943]
### What happened?

Running the `docker-compose.yml` file at https://github.com/mikebrady/shairport-sync/blob/master/docker/docker-compose.yaml with output set either to `pa` or `pw` does not work.

I expect that using the provided `docker-compose.yml` and basic config would produce noises 8)

### Relevant log output

```shell
When:

general =
{
        name = "Soon";
        output_backend = "pw";
}
```

I get the following output:
```
shairport-sync-1  | Starting shairport-sync
shairport-sync-1  | warning: Shairport Sync's PipeWire backend can not get timing information from the PipeWire system. Is PipeWire running?
shairport-sync-1  | warning: Shairport Sync's PipeWire backend can not get timing information from the PipeWire system. Is PipeWire running?
shairport-sync-1  | warning: Shairport Sync's PipeWire backend can not get timing information from the PipeWire system. Is PipeWire running?
```

When:
```
general =
{
        name = "Soon";
        output_backend = "pa";
}
```

I get the following output:
```
shairport-sync-1  | Starting shairport-sync
```
i.e nothing
```


### System Information.

Ubuntu /dev on X1 Carbon Gen 7

### Configuration Information.

```shell
>> Display Config Start.

From "uname -a":
 Linux carbonicus 6.11.0-9-generic #9-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct 14 13:19:59 UTC 2024 x86_64 Linux

From /etc/os-release:
 Alpine Linux v3.17

Shairport Sync Version String:
 4.3.5-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-pw-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Soon";
   output_backend = "pa";
 };
 pw : 
 {
   application_name = "Shairport Sync";
   node_name = "Shairport Sync";
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Could you post the actual `docker-compose.yml` you used, please?

**Comment by spmp** [comment]
Certainly:

```
services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    #restart: unless-stopped
    environment:
    #  S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file
      PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
      PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
      XDG_RUNTIME_DIR: /tmp # Path for pipewire
    #devices:
    #  - "/dev/snd" # ALSA device, omit if using PulseAudio
    volumes:
      - /etc/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
      - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
      - /run/user/1000/pipewire-0:/tmp/pipewire-0 # Pipewire socket when using pipewire
    # command: -o pw # You can specify the desired output with command:
    logging:
      options:
        max-size: "200k"
        max-file: "10"
```

**Comment by spmp** [comment]
So running it all again today and it looks like PulseAudio is working as expected. I am using `pavucontrol` (from PulseAudio) to look for the streams.
Pipewire is not working sadly.

**Comment by rp86** [comment]
I get the same warning in my log: `"audio_pw.c:373" *warning: Shairport Sync's PipeWire backend can not get timing information from the PipeWire system. Is PipeWire running?` however it passes audio fine. Only obvious difference I can see is that I'm using `command: -o pw` in my docker-compose file and have left the output selection and default Pipewire config commented out in my configuration file.

**Comment by spmp** [comment]
@rp86 thank you for sharing this - I am expecting to see a stream in `pavucontrol` and am not - it could be that it is playing fine and that the volume is low - how would I check this please? Please forgive my very PA centric world view.

**Comment by mikebrady** [comment]
Maybe take a look at [this](https://github.com/mikebrady/shairport-sync/discussions/1940)?

**Comment by rp86** [comment]
I do have `S6_KEEP_ENV: 1` uncommented in my working setup.

**Comment by spmp** [comment]
Thank you both,
S6_KEEP_ENV: 1
is the trick! Maybe add to the connect that it's required for pipewire.
And for the record it shows up in pavucontrol even when using the pw
backend.
Now to work out how to run multiple containers 😅

**Comment by spmp** [comment]
Certainly:
I have opted to use the `command` rather than a linked config file, and here they are - basically your example file:

## PipeWire
```yml
# Shairport-sync Docker Compose for PipeWire output
services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    environment:
      S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file, reqd for pipewire
      XDG_RUNTIME_DIR: /tmp # Path for pipewire
    volumes:
      #- /etc/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
      - /run/user/1000/pipewire-0:/tmp/pipewire-0 # Pipewire socket when using pipewire
    command: --output=pw --name='Shairport-sync 🤗' # UTF-8 Emojis work my friends!
    logging:
      options:
        max-size: "200k"
        max-file: "10"
```

## PulseAudio
```yml
# Shairport-sync Docker Compose for PulseAudio output
services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    environment:
      PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
      PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    volumes:
      #- /etc/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
      - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
    command: --output=pa --name='Shairport-sync 🤗' # UTF-8 Emojis work my friends!
    logging:
      options:
        max-size: "200k"
        max-file: "10"
```
