### ISSUE TITLE
[Problem]: v5.0-dev: The pid file "/run/dbus/dbus.pid" exists

### ISSUE THREAD

**Issue by deepsweet** [mikebrady/shairport-sync#2009]
### What happened?

Hi.

Testng v5.0-dev and the only technical issue I've faced so far is:

```
dbus-daemon[9]: Failed to start message bus: The pid file "/run/dbus/dbus.pid" exists, if the message bus is not running, remove this file
```

when I try to `restart` a Docker container. `dbus.pid` persists between the restarts and causes error.

I've seen fixes for the same issue in other projects:

```sh
if [ -f /run/dbus/dbus.pid ]
then
  rm -v /run/dbus/dbus.pid
fi
```

### Relevant log output

```shell

```

### System Information.

Fosi Audio ZD3

### Configuration Information.

```shell
$ shairport-sync --displayConfig

>> Display Config Start.

From "uname -a":
 Linux server 6.8.0-57-generic #59-Ubuntu SMP PREEMPT_DYNAMIC Sat Mar 15 17:40:59 UTC 2025 x86_64 Linux

From /etc/os-release:
 Alpine Linux edge

Shairport Sync Version String:
 5.0-dev-15-g3aa7d1a6-dirty-FFmpeg-OpenSSL-Avahi-ALSA-PulseAudio-PipeWire-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general : 
 {
   name = "Home";
   interpolation = "soxr";
   output_backend = "alsa";
   playback_mode = "stereo";
   eight_channel_mode = "off";
   six_channel_mode = "off";
   mixdown = "off";
   ignore_volume_control = "yes";
 };
 alsa : 
 {
   output_device = "hw:CARD=ZD3";
   output_rate = "auto";
   output_format = "auto";
   output_channels = "auto";
   disable_synchronization = "yes";
 };
 metadata : 
 {
   enabled = "no";
   include_cover_art = "no";
 };
 diagnostics : 
 {
   log_verbosity = 0;
 };

>> Display Config End.
>> Goodbye!
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [x] Confirm

**Comment by mikebrady** [comment]
Thanks. And just to be clear, does:
```
if [ -f /run/dbus/dbus.pid ]
then
  rm -v /run/dbus/dbus.pid
fi
```
fix the problem for you?

**Comment by deepsweet** [comment]
I ended up with the following fix:

`compose.yml`:

```yaml
  airplay:
    image: mikebrady/shairport-sync:development-classic
    entrypoint: /entrypoint.sh
    container_name: airplay
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/snd
    volumes:
      - ./airplay/entrypoint.sh:/entrypoint.sh
      - ./airplay/shairport-sync.conf:/etc/shairport-sync.conf
```

`./airplay/entrypoint.sh`:

```sh
chmod +x ./airplay/entrypoint.sh
```

```sh
#!/bin/sh
if [ -f /run/dbus/dbus.pid ]; then
  rm -v /run/dbus/dbus.pid
fi

if [ -f /run/avahi-daemon/pid ]; then
  rm -v /run/avahi-daemon/pid
fi

exec ./run.sh "$@"
```

So the `dbus.pid` wasn't the only problem, avahi pid issue was actually next in queue:

```
airplay  | removed '/run/dbus/dbus.pid'
airplay  | removed '/run/avahi-daemon/pid'
airplay  | Can not set realtime properties of a thread.
```

Regarding the `Can not set realtime properties of a thread` – I'm not 100% sure, it doesn't hurt and everything works fine.
